export const ROUTES = {
  HOME:                '/',
  LIST:                '/list',
  QUALIFICATION_DETAIL: (id: number | string) => `/qualification/${id}`,
  CALENDAR:            '/calendar',
  ADMIN:               '/admin',
  HELD:                '/held',
  WISHLIST:            '/wishlist',
  ROADMAP:             '/roadmap',
  LOGIN:               '/login',
  REGISTER:            '/register',
  EMAIL_SENT:          '/email-sent',
  SET_PASSWORD:        '/set-password',
  FORGOT_PASSWORD:     '/forgot-password',
  RESET_PASSWORD:      '/reset-password',
  PROFILE:             '/me',
  PRICING:             '/pricing',
  PRIVACY:             '/privacy',
  TERMS:               '/terms',
  TOKUSHO:             '/tokusho',
  SUPPORT:             '/support',
} as const;
