import { SeedQualification } from '../../types/index.js';

export const seedQualifications: SeedQualification[] = [
  // ─── 国家資格 / IT・情報 ───────────────────────────────────────────
  { name: 'ITパスポート試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/ip.html', description: 'ITの基礎知識を認定する国家資格（CBT方式・随時受験）', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: '基本情報技術者試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/fe.html', description: 'ITエンジニアの登竜門となる国家資格', is_scrapable: true, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: '応用情報技術者試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/ap.html', description: 'ITの応用的な知識・技能を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '情報安全確保支援士試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/sc.html', description: 'サイバーセキュリティ対策の専門家を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ネットワークスペシャリスト試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/nw.html', description: 'ネットワーク技術の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'データベーススペシャリスト試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/db.html', description: 'データベース技術の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'プロジェクトマネージャ試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/pm.html', description: 'プロジェクトマネジメントの専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'システムアーキテクト試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/sa.html', description: 'システムアーキテクチャ設計の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ITストラテジスト試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/st.html', description: 'IT戦略の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'システム監査技術者試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/au.html', description: 'システム監査の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ITサービスマネージャ試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/sm.html', description: 'ITサービスマネジメントの専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'エンベデッドシステムスペシャリスト試験', main_category: '国家資格', sub_category: 'IT・情報', official_url: 'https://www.ipa.go.jp/shiken/kubun/es.html', description: '組み込みシステム技術の専門家を認定する高度情報処理技術者試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 民間資格 / クラウド / AWS ────────────────────────────────────
  { name: 'AWS Certified Cloud Practitioner', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-cloud-practitioner/', description: 'AWSクラウドの基礎知識を認定する入門レベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Solutions Architect - Associate', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-solutions-architect-associate/', description: 'AWSソリューション設計のアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Solutions Architect - Professional', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-solutions-architect-professional/', description: 'AWSソリューション設計のプロフェッショナルレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Developer - Associate', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-developer-associate/', description: 'AWS上でのアプリケーション開発スキルを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified SysOps Administrator - Associate', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-sysops-admin-associate/', description: 'AWSシステム運用スキルを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified DevOps Engineer - Professional', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-devops-engineer-professional/', description: 'AWSでのDevOpsプラクティスを認定するプロフェッショナルレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Advanced Networking - Specialty', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-advanced-networking-specialty/', description: 'AWS高度なネットワーキングを認定する専門資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Security - Specialty', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-security-specialty/', description: 'AWSセキュリティを認定する専門資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Machine Learning - Specialty', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-machine-learning-specialty/', description: 'AWS機械学習を認定する専門資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Database - Specialty', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-database-specialty/', description: 'AWSデータベースを認定する専門資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'AWS Certified Data Analytics - Specialty', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://aws.amazon.com/jp/certification/certified-data-analytics-specialty/', description: 'AWSデータ分析を認定する専門資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },

  // ─── 民間資格 / クラウド / GCP ────────────────────────────────────
  { name: 'Google Cloud Associate Cloud Engineer', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/cloud-engineer', description: 'Google Cloudの基本的なデプロイ・管理スキルを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },
  { name: 'Google Cloud Professional Cloud Architect', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/cloud-architect', description: 'Google Cloudソリューションの設計・管理スキルを認定するプロフェッショナル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },
  { name: 'Google Cloud Professional Data Engineer', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/data-engineer', description: 'Google Cloudデータエンジニアリングスキルを認定するプロフェッショナル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },
  { name: 'Google Cloud Professional Cloud Developer', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/cloud-developer', description: 'Google Cloudアプリケーション開発スキルを認定するプロフェッショナル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },
  { name: 'Google Cloud Professional Cloud Security Engineer', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/cloud-security-engineer', description: 'Google Cloudセキュリティを認定するプロフェッショナル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },
  { name: 'Google Cloud Professional Machine Learning Engineer', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://cloud.google.com/learn/certification/machine-learning-engineer', description: 'Google Cloud機械学習エンジニアリングを認定するプロフェッショナル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },

  // ─── 民間資格 / クラウド / Azure ──────────────────────────────────
  { name: 'Microsoft Azure Fundamentals (AZ-900)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-fundamentals/', description: 'Microsoft Azureの基礎知識を認定するファンダメンタルズ資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Microsoft Azure Administrator (AZ-104)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-administrator/', description: 'Azure管理スキルを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Microsoft Azure Developer Associate (AZ-204)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-developer/', description: 'Azureアプリケーション開発スキルを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Microsoft Azure Solutions Architect Expert (AZ-305)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-solutions-architect/', description: 'Azureソリューション設計の高度なスキルを認定するエキスパート資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Microsoft Azure DevOps Engineer Expert (AZ-400)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/devops-engineer/', description: 'Azure DevOpsの高度なスキルを認定するエキスパート資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Microsoft Azure Security Engineer Associate (AZ-500)', main_category: '民間資格', sub_category: 'クラウド', official_url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-security-engineer/', description: 'Azureセキュリティを認定するアソシエイトレベルの資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 民間資格 / データベース ──────────────────────────────────────
  { name: 'Oracle Master Bronze DBA 2019', main_category: '民間資格', sub_category: 'データベース', official_url: 'https://education.oracle.com/ja/oracle-certification-path/pFamily_32', description: 'Oracle Databaseの基礎知識を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Oracle Master Silver DBA 2019', main_category: '民間資格', sub_category: 'データベース', official_url: 'https://education.oracle.com/ja/oracle-certification-path/pFamily_32', description: 'Oracle Databaseの中級知識を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Oracle Master Gold DBA 2019', main_category: '民間資格', sub_category: 'データベース', official_url: 'https://education.oracle.com/ja/oracle-certification-path/pFamily_32', description: 'Oracle Databaseの上級知識を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Oracle Master Platinum DBA 2019', main_category: '民間資格', sub_category: 'データベース', official_url: 'https://education.oracle.com/ja/oracle-certification-path/pFamily_32', description: 'Oracle Databaseの最高位認定資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 民間資格 / プログラミング言語 ───────────────────────────────
  { name: 'Java SE 11 Silver (1Z0-815)', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://education.oracle.com/ja/java-se-11-programmer-i/pexam_1Z0-815', description: 'Java SE 11プログラミングの基礎を認定するOracle資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Java SE 11 Gold (1Z0-816)', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://education.oracle.com/ja/java-se-11-programmer-ii/pexam_1Z0-816', description: 'Java SE 11プログラミングの上級を認定するOracle資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Java SE 17 Developer (1Z0-829)', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://education.oracle.com/ja/java-se-17-developer/pexam_1Z0-829', description: 'Java SE 17プログラミングを認定するOracle資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Java SE 21 Developer (1Z0-830)', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://education.oracle.com/ja/oracle-certified-professional-java-se-21-developer/pexam_1Z0-830', description: 'Java SE 21プログラミングを認定するOracle資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Python 3 エンジニア認定基礎試験', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.pythonic-exam.com/exam/basic', description: 'Python3の基礎文法を認定する民間資格（CBT方式）', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Python 3 エンジニア認定データ分析試験', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.pythonic-exam.com/exam/analysis', description: 'Pythonを使ったデータ分析スキルを認定する民間資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'PHP技術者認定試験 初級', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.php-others.jp/exam/primary/', description: 'PHPの基礎知識を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'PHP技術者認定試験 上級', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.php-others.jp/exam/advance/', description: 'PHPの上級知識を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Ruby技術者認定試験 Silver', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.ruby.or.jp/ja/certification/examination/', description: 'Ruby基礎文法を認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Ruby技術者認定試験 Gold', main_category: '民間資格', sub_category: 'プログラミング言語', official_url: 'https://www.ruby.or.jp/ja/certification/examination/', description: 'Ruby上級スキルを認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 民間資格 / セキュリティ ──────────────────────────────────────
  { name: 'CompTIA Security+', main_category: '民間資格', sub_category: 'セキュリティ', official_url: 'https://www.comptia.org/ja/certifications/security', description: 'IT基礎セキュリティスキルを認定するグローバル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CompTIA CySA+', main_category: '民間資格', sub_category: 'セキュリティ', official_url: 'https://www.comptia.org/ja/certifications/cybersecurity-analyst', description: 'サイバーセキュリティアナリストを認定するグローバル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CompTIA CASP+', main_category: '民間資格', sub_category: 'セキュリティ', official_url: 'https://www.comptia.org/certifications/comptia-advanced-security-practitioner', description: '上級セキュリティプラクティショナーを認定するグローバル資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CISSP', main_category: '民間資格', sub_category: 'セキュリティ', official_url: 'https://www.isc2.org/certifications/cissp', description: 'ISC2認定の情報セキュリティ最高峰資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CEH (認定倫理ハッカー)', main_category: '民間資格', sub_category: 'セキュリティ', official_url: 'https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/', description: 'EC-Council認定の倫理的ハッキングスキルを認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },

  // ─── 民間資格 / ネットワーク ──────────────────────────────────────
  { name: 'CCNA', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.cisco.com/c/ja_jp/training-events/training-certifications/certifications/associate/ccna.html', description: 'Cisco認定ネットワークアソシエイト資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CCNP Enterprise', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.cisco.com/c/ja_jp/training-events/training-certifications/certifications/professional/ccnp-enterprise.html', description: 'Cisco認定ネットワークプロフェッショナル（エンタープライズ）資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CCNP Security', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.cisco.com/c/ja_jp/training-events/training-certifications/certifications/professional/ccnp-security.html', description: 'Cisco認定ネットワークプロフェッショナル（セキュリティ）資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'LPIC-1 (Linux管理者)', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.lpi.org/ja/our-certifications/lpic-1-overview/', description: 'Linux基礎管理を認定するLPI資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'LPIC-2 (Linuxエンジニア)', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.lpi.org/ja/our-certifications/lpic-2-overview/', description: 'Linux上級管理を認定するLPI資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'LPIC-3 (Linuxマスター)', main_category: '民間資格', sub_category: 'ネットワーク', official_url: 'https://www.lpi.org/ja/our-certifications/lpic-3-overview/', description: 'Linux専門家を認定するLPI最高位資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 民間資格 / プロジェクト管理 ─────────────────────────────────
  { name: 'PMP (Project Management Professional)', main_category: '民間資格', sub_category: 'プロジェクト管理', official_url: 'https://www.pmi.org/certifications/project-management-pmp', description: 'PMI認定のプロジェクトマネジメント国際資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 3 },
  { name: 'CAPM (準プロジェクトマネジメント専門家)', main_category: '民間資格', sub_category: 'プロジェクト管理', official_url: 'https://www.pmi.org/certifications/certified-associate-capm', description: 'PMI認定の準プロジェクトマネジメント資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 5 },
  { name: 'ITIL 4 Foundation', main_category: '民間資格', sub_category: 'プロジェクト管理', official_url: 'https://www.axelos.com/certifications/itil-service-management/itil-4-foundation', description: 'ITサービスマネジメントの標準フレームワークを認定する資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'Scrum Master認定 (PSM I)', main_category: '民間資格', sub_category: 'プロジェクト管理', official_url: 'https://www.scrum.org/assessments/professional-scrum-master-i-certification', description: 'Scrumフレームワーク実践を認定するScrum.org資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'CSM (認定スクラムマスター)', main_category: '民間資格', sub_category: 'プロジェクト管理', official_url: 'https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster', description: 'Scrum Alliance認定のスクラムマスター資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: true, renewal_period_years: 2 },

  // ─── 民間資格 / データ・AI ────────────────────────────────────────
  { name: 'G検定 (ジェネラリスト検定)', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://www.jdla.org/certificate/general/', description: 'AI・ディープラーニングの基礎知識を認定するJDLA資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'E資格 (エンジニア資格)', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://www.jdla.org/certificate/engineer/', description: 'ディープラーニングの実装スキルを認定するJDLA資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'データサイエンティスト検定 (DS検定)', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://www.datascientist.or.jp/dskentei/', description: 'データサイエンスの基礎スキルを認定する検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '統計検定 2級', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://www.toukei-kentei.jp/exam/grade2/', description: '統計学の基礎知識・活用力を認定する公的検定（CBT方式）', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: '統計検定 1級', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://www.toukei-kentei.jp/exam/grade1/', description: '統計学の高度な専門知識を認定する公的検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'データベーススペシャリスト (民間版)', main_category: '民間資格', sub_category: 'データ・AI', official_url: 'https://oss-db.jp/', description: 'OSS-DBのデータベース技術者認定資格（Silver/Gold）', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 公的資格 / 語学 ──────────────────────────────────────────────
  { name: '実用英語技能検定 (英検) 1級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.eiken.or.jp/eiken/exam/', description: '最高レベルの英語力を認定する公的資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '実用英語技能検定 (英検) 準1級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.eiken.or.jp/eiken/exam/', description: '上位レベルの英語力を認定する公的資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '実用英語技能検定 (英検) 2級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.eiken.or.jp/eiken/exam/', description: '高校卒業程度の英語力を認定する公的資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '実用英語技能検定 (英検) 準2級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.eiken.or.jp/eiken/exam/', description: '高校中級程度の英語力を認定する公的資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '実用英語技能検定 (英検) 3級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.eiken.or.jp/eiken/exam/', description: '中学卒業程度の英語力を認定する公的資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'TOEIC Listening & Reading Test', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.iibc-global.org/toeic/test/lr.html', description: 'ビジネス英語のリスニング・リーディング力を測定するテスト', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'TOEIC Speaking & Writing Tests', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.iibc-global.org/toeic/test/sw.html', description: 'ビジネス英語のスピーキング・ライティング力を測定するテスト', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'TOEFL iBT', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.ets.org/toefl', description: '英語4技能を測定する海外大学入学等に必要なテスト', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'IELTS', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.ielts.org/', description: '英語4技能を測定する国際的な英語能力テスト', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },
  { name: 'HSK 6級 (中国語検定)', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.hsk.or.jp/', description: '中国語最高位の語学力を認定する国際検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'HSK 5級 (中国語検定)', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.hsk.or.jp/', description: '中国語上位の語学力を認定する国際検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '日本語能力試験 (JLPT) N1', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.jlpt.jp/', description: '最高レベルの日本語能力を認定する国際的な試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '日本語能力試験 (JLPT) N2', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.jlpt.jp/', description: '高レベルの日本語能力を認定する国際的な試験', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '中国語検定 2級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.chuken.gr.jp/', description: '中国語の実用能力を認定する日本中国語検定協会の検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ドイツ語技能検定試験 (独検) 2級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.dokken.or.jp/', description: 'ドイツ語の実用能力を認定する公益財団法人の検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'フランス語技能検定試験 (仏検) 2級', main_category: '公的資格', sub_category: '語学', official_url: 'https://www.apefdapf.org/', description: 'フランス語の実用能力を認定する公益財団法人の検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 公的資格 / 会計・簿記 ───────────────────────────────────────
  { name: '日商簿記 1級', main_category: '公的資格', sub_category: '会計・簿記', official_url: 'https://www.kentei.ne.jp/bookkeeping/', description: '高度な簿記・会計知識を認定する日本商工会議所主催の検定', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '日商簿記 2級', main_category: '公的資格', sub_category: '会計・簿記', official_url: 'https://www.kentei.ne.jp/bookkeeping/', description: '商業・工業簿記の知識を認定する日本商工会議所主催の検定', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '日商簿記 3級', main_category: '公的資格', sub_category: '会計・簿記', official_url: 'https://www.kentei.ne.jp/bookkeeping/', description: '基礎的な簿記の知識を認定する日本商工会議所主催の検定', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '全商簿記実務検定 1級', main_category: '公的資格', sub_category: '会計・簿記', official_url: 'https://www.zensho.or.jp/kentei/bookkeeping/', description: '全国商業高等学校協会主催の簿記実務検定', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 法律・行政 ───────────────────────────────────────
  { name: '宅地建物取引士 (宅建士)', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.retio.or.jp/', description: '不動産取引の専門家を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '行政書士', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://gyosei-shiken.or.jp/', description: '行政手続の専門家を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '社会保険労務士 (社労士)', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.sharosi-siken.or.jp/', description: '労働・社会保険の専門家を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '司法書士', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.moj.go.jp/shihouseido/shihouseido01.html', description: '登記・裁判手続き等の法律専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '弁理士', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.jpo.go.jp/indexj.htm', description: '知的財産権の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '中小企業診断士', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.j-smeca.jp/contents/010_c_/010_shikenmondai.html', description: '中小企業の経営コンサルタントを認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'マンション管理士', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.mankan.org/exam.html', description: 'マンション管理の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '管理業務主任者', main_category: '国家資格', sub_category: '法律・行政', official_url: 'https://www.mankan.org/exam.html', description: 'マンション管理業の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 会計・税務 ───────────────────────────────────────
  { name: '公認会計士', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.fsa.go.jp/cpaaob/', description: '会計・監査の最高峰国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '税理士', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.nta.go.jp/taxes/zeirishi/zeirishishiken/', description: '税務の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ファイナンシャルプランナー 1級 (FP1級)', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.jafp.or.jp/exam/', description: '最高レベルの金融・ライフプランニング知識を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ファイナンシャルプランナー 2級 (FP2級)', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.jafp.or.jp/exam/', description: '上位の金融・ライフプランニング知識を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: 'ファイナンシャルプランナー 3級 (FP3級)', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.jafp.or.jp/exam/', description: '基礎的な金融・ライフプランニング知識を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '証券外務員 一種', main_category: '国家資格', sub_category: '会計・税務', official_url: 'https://www.jsda.or.jp/manabu/gaimu/index.html', description: '金融商品の取引を行うための国家資格', is_scrapable: false, exam_format: 'anytime', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 建設・不動産 ─────────────────────────────────────
  { name: '建築士 1級', main_category: '国家資格', sub_category: '建設・不動産', official_url: 'https://www.jaeic.or.jp/shiken/1k/', description: '建築設計・工事監理の最高位国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '建築士 2級', main_category: '国家資格', sub_category: '建設・不動産', official_url: 'https://www.jaeic.or.jp/shiken/2k/', description: '中規模建築の設計・工事監理を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '建築士 木造', main_category: '国家資格', sub_category: '建設・不動産', official_url: 'https://www.jaeic.or.jp/shiken/mk/', description: '木造建築の設計・工事監理を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '1級建築施工管理技士', main_category: '国家資格', sub_category: '建設・不動産', official_url: 'https://www.fcip-shiken.jp/ken1/', description: '大規模建築工事の施工管理を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '2級建築施工管理技士', main_category: '国家資格', sub_category: '建設・不動産', official_url: 'https://www.fcip-shiken.jp/ken2/', description: '中小規模建築工事の施工管理を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 工業・電気 ───────────────────────────────────────
  { name: '電気工事士 第1種', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shiken.or.jp/examination/e-construction01.html', description: '大規模電気工事を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '電気工事士 第2種', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shiken.or.jp/examination/e-construction02.html', description: '一般住宅・小規模電気工事を認定する国家資格', is_scrapable: true, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '第三種電気主任技術者 (電験三種)', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shiken.or.jp/examination/e-chief03.html', description: '電気設備の保安・管理を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '危険物取扱者 乙種4類', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shoubo-shiken.or.jp/kikenbutsu/', description: '引火性液体（ガソリン等）の取り扱いを認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '危険物取扱者 甲種', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shoubo-shiken.or.jp/kikenbutsu/', description: '全種類の危険物の取り扱いを認定する最高位の国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '消防設備士 甲種', main_category: '国家資格', sub_category: '工業・電気', official_url: 'https://www.shoubo-shiken.or.jp/shoubou/', description: '消防設備の設置・工事・点検を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 医療・福祉 ───────────────────────────────────────
  { name: '看護師', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000162173.html', description: '患者の医療処置・療養上の世話を行う国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '保健師', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000162178.html', description: '地域住民の健康管理・保健指導を行う国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '薬剤師', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000162172.html', description: '薬の調剤・管理・指導を行う国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '理学療法士 (PT)', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000049373.html', description: '身体機能の回復・維持を支援するリハビリ専門職の国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '作業療法士 (OT)', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000049374.html', description: '日常生活能力の回復を支援するリハビリ専門職の国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '介護福祉士', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.sssc.or.jp/kaigo/shiken/', description: '介護の専門的な知識・技術を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '社会福祉士', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.sssc.or.jp/shakai/shiken/', description: '福祉相談援助の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '精神保健福祉士', main_category: '国家資格', sub_category: '医療・福祉', official_url: 'https://www.sssc.or.jp/seishin/shiken/', description: '精神障害者の福祉相談援助の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },

  // ─── 国家資格 / 食品・調理 ───────────────────────────────────────
  { name: '調理師', main_category: '国家資格', sub_category: '食品・調理', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000095403.html', description: '調理の技術・知識を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '栄養士', main_category: '国家資格', sub_category: '食品・調理', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000095398.html', description: '栄養指導・食事管理の専門家を認定する国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '管理栄養士', main_category: '国家資格', sub_category: '食品・調理', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000095398.html', description: '高度な栄養指導・食事療法を行う国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
  { name: '食品衛生管理者', main_category: '国家資格', sub_category: '食品・調理', official_url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000095398.html', description: '食品の製造・加工現場の衛生管理を担う国家資格', is_scrapable: false, exam_format: 'fixed_date', requires_renewal: false, renewal_period_years: null },
];
